baseurl: ''
url: 'https://casaventa.co'
name: H. Franco, propietario
author: H. Franco, propietario
title: Vendo mi casa en San Agustín Huila | H. Franco, propietario
whatsapp: "https://api.whatsapp.com/send?phone=+573202492786&text=%F0%9F%91%B7%F0%9F%8F%BC%20Hola.%20Quiero%20vender%20mi%20casa%20en%20tu%20web%20casaventa.co"

permalink: :slug

markdown: kramdown

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []
